language: node_js
node_js:
  - '0.10'
before_install:
  - 'npm install npm -g && npm install codeclimate-test-reporter -g'
addons:
  code_climate:
    repo_token: 91fe7daacc6d0e8880d29bb37bb83aad99341a2b053798930a8f82e59d4126d5
after_script:
  - 'npm run gen-coverage && cat lcov.info | codeclimate-test-reporter'
